version: '3'
services:
  agendamentosapp:
    container_name: agendamentos
    build:
      context: .
      dockerfile: project/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=dbAgendamentos
    depends_on:
      - dbAgendamentos
    networks:
      - app-network

  dbAgendamentos:
    container_name: dbAgendamentos
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    external: true